---
# tasks file for certbot-gcp
- name: check if certbot-dns-google plugin is installed
  shell: "certbot plugins 2>/dev/null|grep dns-google"
  register: cf_check
  ignore_errors: true
  changed_when: "cf_check is failed"

- name: Install certbot-dns-google plugin
  apt:
    name: python3-certbot-dns-google
    state: present

- name: Create certbot folder - sudouser
  file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Certbot Template
  template:
    src: 'templates/letsencrypt_cli.ini.j2'
    dest: '/etc/letsencrypt/cli.ini'
    owner: root
    group: root
    mode: 0600

- name: Create GCP DNS Credentials
  copy:
    content: "{{ certbot_gcp_credentials }}"
    dest: "/etc/letsencrypt/dnsgoogle.json"
    owner: root
    group: root
    mode: 0600
- name: Dump Vars
  debug:
    var: vars
- name: Create Certs.
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_create_if_missing: true
    certbot_create_method: "standalone"




